packages:
  - apps/*
  - packages/*

allowBuilds:
  '@prisma/engines': true
  '@sentry/cli': true
  esbuild: true
  prisma: true
  sharp: true

overrides:
  deepmerge-ts: 8.0.0
  fast-uri: 3.1.6
  mysql2: 3.22.0

catalog:
  typescript: ^6.0.3
  vitest: ^4.1.10
  zod: ^4.4.3

minimumReleaseAgeExclude:
  - '@expo/cli@57.0.14 || 57.0.17 || 57.0.18'
  - '@expo/fingerprint@0.20.7 || 0.20.9 || 0.20.10'
  - '@expo/inline-modules@0.1.5'
  - '@expo/local-build-cache-provider@57.0.6 || 57.0.7'
  - '@expo/metro-config@57.0.8 || 57.0.9 || 57.0.10'
  - '@expo/prebuild-config@57.0.11 || 57.0.13 || 57.0.14'
  - expo-asset@57.0.10 || 57.0.13 || 57.0.14
  - expo-constants@57.0.10 || 57.0.13 || 57.0.14
  - expo-server@57.0.2
  - expo@57.0.12 || 57.0.15 || 57.0.16
  - '@expo/metro-runtime@57.0.9 || 57.0.12 || 57.0.13'
  - '@expo/ui@57.0.10 || 57.0.12 || 57.0.13'
  - expo-router@57.0.12 || 57.0.15 || 57.0.16
  - expo-image-picker@57.0.9 || 57.0.12 || 57.0.13
  - '@expo/router-server@57.0.7'
  - expo-file-system@57.0.5
  - expo-modules-core@57.0.12 || 57.0.13
  - expo-modules-jsi@57.0.5
  - expo-dev-client@57.0.14 || 57.0.15
  - expo-dev-launcher@57.0.14 || 57.0.15
  - expo-dev-menu@57.0.14 || 57.0.15
  - expo-linking@57.0.7
  - expo-notifications@57.0.13 || 57.0.14
  - expo-updates@57.0.16 || 57.0.17
  - '@expo/config-plugins@57.0.9'
  - '@expo/config@57.0.9'
  - '@expo/image-utils@0.11.5'
  - '@expo/metro-file-map@57.0.2'
  - '@expo/require-utils@57.0.5'
  - babel-preset-expo@57.0.8
  - expo-modules-autolinking@57.0.11
  - expo-crypto@57.0.2
  - expo-splash-screen@57.0.8
