export { createPrismaClient, getPrismaClient } from './client';
export {
  AccountStatus,
  CurrencyCode,
  ListingCondition,
  ListingStatus,
  MessageFlagCategory,
  MessageFlagStatus,
  MessageModerationState,
  ModerationAuditAction,
  ModerationReportStatus,
  NotificationOutboxStatus,
  NotificationType,
  OrderActorType,
  OrderEventType,
  OrderStatus,
  PaymentMethod,
  PaymentProviderCode,
  PaymentStatus,
  PhoneVerificationAttemptStatus,
  PhoneVerificationProvider,
  Prisma,
  PrismaClient,
  ReportReason,
  ReportTargetType,
  ShipmentStatus,
  PushDeliveryStatus,
  PushPlatform,
  UserRole,
} from './generated/client/client';
export type {
  Address,
  Category,
  Conversation,
  Follow,
  Listing,
  ListingImage,
  ListingLike,
  Message,
  MessageModerationAudit,
  MessageModerationFlag,
  ModerationAudit,
  ModerationReport,
  Notification,
  NotificationOutbox,
  Order,
  OrderEvent,
  Payment,
  PaymentProviderEvent,
  PhoneVerificationAttempt,
  Profile,
  SavedListing,
  Shipment,
  PushDelivery,
  PushDevice,
  User,
} from './generated/client/client';

export const DATABASE_PROVIDER = 'postgresql' as const;
