export const DEMO_NAMESPACE = 'demo-marketplace-v1' as const;
export const DEMO_PROJECT_REF = 'dstnxzljsbyusxoogkzr' as const;
export const DEMO_CONFIRMATION = 'THRIFTAGE_SYNTHETIC_STAGING_ONLY' as const;

export interface DemoSeller {
  readonly username: string;
  readonly fullName: string;
  readonly bio: string;
  readonly university: string;
  readonly location: string;
}

export interface DemoListing {
  readonly seller: string;
  readonly title: string;
  readonly category: string;
  readonly priceMinor: number;
  readonly condition: 'NEW' | 'LIKE_NEW' | 'GOOD' | 'FAIR';
  readonly size: string;
  readonly color: string;
  readonly colorFamily:
    | 'BLACK'
    | 'WHITE'
    | 'GREY'
    | 'BROWN'
    | 'BEIGE'
    | 'RED'
    | 'GREEN'
    | 'BLUE'
    | 'PURPLE'
    | 'PINK'
    | 'METALLIC'
    | 'MULTICOLOR';
  readonly fitType: 'OVERSIZED' | 'RELAXED' | 'REGULAR' | 'SLIM' | 'TAILORED';
  readonly garmentRole:
    'TOP' | 'BOTTOM' | 'DRESS' | 'OUTERWEAR' | 'SHOES' | 'BAG' | 'JEWELRY' | 'ACCESSORY' | 'OTHER';
  readonly sizeSystem: 'ALPHA' | 'SHOE_EU' | 'ONE_SIZE';
  readonly sizeKey: string;
  readonly styles: readonly string[];
  readonly status: 'ACTIVE' | 'DRAFT' | 'PENDING_REVIEW' | 'REJECTED' | 'SOLD' | 'ARCHIVED';
  readonly assetGroup: string;
  readonly panel: number;
  readonly rejectionReason?: string;
}

export const demoSellers: readonly DemoSeller[] = [
  {
    username: 'neutralarchive',
    fullName: 'Areeba Khan',
    bio: 'Quiet staples, natural textures, and an easy neutral wardrobe.',
    university: 'Lahore School of Economics',
    location: 'Lahore',
  },
  {
    username: 'lahorelayers',
    fullName: 'Rayyan Malik',
    bio: 'Streetwear layers and utility pieces selected for everyday city wear.',
    university: 'LUMS',
    location: 'Lahore',
  },
  {
    username: 'sundaywardrobe',
    fullName: 'Maira Siddiqui',
    bio: 'Polished smart-casual pieces with timeless tailoring.',
    university: 'IBA Karachi',
    location: 'Karachi',
  },
  {
    username: 'secondspinpk',
    fullName: 'Zainab Qureshi',
    bio: 'Vintage finds with honest condition notes and plenty of character.',
    university: 'Beaconhouse National University',
    location: 'Lahore',
  },
  {
    username: 'afterhourscloset',
    fullName: 'Hania Raza',
    bio: 'Dark eveningwear, statement texture, and party-ready accessories.',
    university: 'Indus Valley School of Art and Architecture',
    location: 'Karachi',
  },
  {
    username: 'y2kbyzoya',
    fullName: 'Zoya Ahmed',
    bio: 'Playful Y2K colour, cropped knits, and nostalgic accessories.',
    university: 'NED University',
    location: 'Karachi',
  },
  {
    username: 'modestmusepk',
    fullName: 'Ayesha Noor',
    bio: 'Modern modestwear for campus, dinners, and wedding season.',
    university: 'Kinnaird College',
    location: 'Lahore',
  },
  {
    username: 'sneakerroompk',
    fullName: 'Hamza Ali',
    bio: 'Clean sneakers and practical athleisure in wearable condition.',
    university: 'FAST NUCES',
    location: 'Islamabad',
  },
  {
    username: 'studioformal',
    fullName: 'Daniyal Shah',
    bio: 'Tailored formalwear for presentations, dinners, and events.',
    university: 'NUST',
    location: 'Islamabad',
  },
  {
    username: 'campuscloset',
    fullName: 'Mehak Tariq',
    bio: 'Affordable everyday campus layers, denim, and dependable basics.',
    university: 'Punjab University',
    location: 'Lahore',
  },
  {
    username: 'smallthingspk',
    fullName: 'Sara Iqbal',
    bio: 'Bags, jewellery, and finishing pieces for repeat wear.',
    university: 'COMSATS University',
    location: 'Islamabad',
  },
  {
    username: 'karachiedit',
    fullName: 'Alina Mir',
    bio: 'Contemporary silhouettes and dinner-ready colour from Karachi.',
    university: 'Habib University',
    location: 'Karachi',
  },
] as const;

type Product = Omit<DemoListing, 'seller' | 'status' | 'assetGroup' | 'panel'>;

const product = (
  title: string,
  category: string,
  priceMinor: number,
  condition: DemoListing['condition'],
  size: string,
  color: string,
  colorFamily: DemoListing['colorFamily'],
  fitType: DemoListing['fitType'],
  garmentRole: DemoListing['garmentRole'],
  sizeSystem: DemoListing['sizeSystem'],
  sizeKey: string,
  styles: readonly string[],
): Product => ({
  title,
  category,
  priceMinor,
  condition,
  size,
  color,
  colorFamily,
  fitType,
  garmentRole,
  sizeSystem,
  sizeKey,
  styles,
});

const activeCollections: Readonly<Record<string, readonly Product[]>> = {
  neutralarchive: [
    product(
      'Minimal White Linen Shirt',
      'tops',
      235000,
      'LIKE_NEW',
      'M',
      'White',
      'WHITE',
      'RELAXED',
      'TOP',
      'ALPHA',
      'M',
      ['minimalist', 'smart-casual'],
    ),
    product(
      'Oatmeal Ribbed Knit Cardigan',
      'tops',
      315000,
      'GOOD',
      'M',
      'Oatmeal',
      'BEIGE',
      'RELAXED',
      'TOP',
      'ALPHA',
      'M',
      ['minimalist', 'old-money'],
    ),
    product(
      'Stone Wide-Leg Trousers',
      'bottoms',
      285000,
      'LIKE_NEW',
      'M',
      'Stone',
      'BEIGE',
      'TAILORED',
      'BOTTOM',
      'ALPHA',
      'M',
      ['minimalist', 'smart-casual'],
    ),
    product(
      'Charcoal Everyday T-Shirt',
      'tops',
      145000,
      'GOOD',
      'M',
      'Charcoal',
      'GREY',
      'REGULAR',
      'TOP',
      'ALPHA',
      'M',
      ['minimalist'],
    ),
    product(
      'Cream Column Midi Dress',
      'dresses-one-pieces',
      425000,
      'LIKE_NEW',
      'M',
      'Cream',
      'BEIGE',
      'SLIM',
      'DRESS',
      'ALPHA',
      'M',
      ['minimalist', 'formal'],
    ),
  ],
  lahorelayers: [
    product(
      'Oversized Forest Green Hoodie',
      'tops',
      325000,
      'GOOD',
      'L',
      'Forest green',
      'GREEN',
      'OVERSIZED',
      'TOP',
      'ALPHA',
      'L',
      ['streetwear'],
    ),
    product(
      'Black Utility Cargo Trousers',
      'bottoms',
      345000,
      'LIKE_NEW',
      'L',
      'Black',
      'BLACK',
      'RELAXED',
      'BOTTOM',
      'ALPHA',
      'L',
      ['streetwear', 'techwear'],
    ),
    product(
      'Graphite Windbreaker Jacket',
      'clothing',
      455000,
      'GOOD',
      'L',
      'Black',
      'BLACK',
      'RELAXED',
      'OUTERWEAR',
      'ALPHA',
      'L',
      ['streetwear', 'techwear'],
    ),
    product(
      'Washed Graphic-Free Tee',
      'tops',
      165000,
      'GOOD',
      'XL',
      'Washed charcoal',
      'GREY',
      'OVERSIZED',
      'TOP',
      'ALPHA',
      'XL',
      ['streetwear'],
    ),
    product(
      'Black High-Top Sneakers',
      'sneakers',
      430000,
      'LIKE_NEW',
      'EU 43',
      'Black',
      'BLACK',
      'REGULAR',
      'SHOES',
      'SHOE_EU',
      '43',
      ['streetwear'],
    ),
  ],
  sundaywardrobe: [
    product(
      'Navy Tailored Trousers',
      'bottoms',
      380000,
      'LIKE_NEW',
      'M',
      'Navy',
      'BLUE',
      'TAILORED',
      'BOTTOM',
      'ALPHA',
      'M',
      ['old-money', 'smart-casual'],
    ),
    product(
      'Ivory Oxford Shirt',
      'tops',
      260000,
      'GOOD',
      'M',
      'Ivory',
      'WHITE',
      'REGULAR',
      'TOP',
      'ALPHA',
      'M',
      ['old-money', 'smart-casual'],
    ),
    product(
      'Camel Knit Polo',
      'tops',
      330000,
      'LIKE_NEW',
      'M',
      'Camel',
      'BEIGE',
      'REGULAR',
      'TOP',
      'ALPHA',
      'M',
      ['old-money'],
    ),
    product(
      'Brown Penny Loafers',
      'other-footwear',
      590000,
      'GOOD',
      'EU 41',
      'Brown',
      'BROWN',
      'REGULAR',
      'SHOES',
      'SHOE_EU',
      '41',
      ['old-money', 'smart-casual'],
    ),
    product(
      'Structured Beige Blazer',
      'clothing',
      680000,
      'LIKE_NEW',
      'M',
      'Beige',
      'BEIGE',
      'TAILORED',
      'OUTERWEAR',
      'ALPHA',
      'M',
      ['old-money', 'formal'],
    ),
  ],
  secondspinpk: [
    product(
      'Vintage Washed Denim Jacket',
      'clothing',
      520000,
      'GOOD',
      'M',
      'Washed blue',
      'BLUE',
      'RELAXED',
      'OUTERWEAR',
      'ALPHA',
      'M',
      ['vintage', 'streetwear'],
    ),
    product(
      'Retro Brown Leather Jacket',
      'clothing',
      2050000,
      'GOOD',
      'L',
      'Cognac brown',
      'BROWN',
      'REGULAR',
      'OUTERWEAR',
      'ALPHA',
      'L',
      ['vintage'],
    ),
    product(
      'Faded Straight-Leg Jeans',
      'bottoms',
      295000,
      'GOOD',
      'M',
      'Faded blue',
      'BLUE',
      'REGULAR',
      'BOTTOM',
      'ALPHA',
      'M',
      ['vintage'],
    ),
    product(
      'Burgundy Corduroy Shirt',
      'tops',
      275000,
      'GOOD',
      'M',
      'Burgundy',
      'RED',
      'RELAXED',
      'TOP',
      'ALPHA',
      'M',
      ['vintage'],
    ),
    product(
      '90s Floral Midi Dress',
      'dresses-one-pieces',
      390000,
      'GOOD',
      'M',
      'Floral',
      'MULTICOLOR',
      'REGULAR',
      'DRESS',
      'ALPHA',
      'M',
      ['vintage'],
    ),
  ],
  afterhourscloset: [
    product(
      'Black Faux-Leather Chelsea Boots',
      'other-footwear',
      620000,
      'LIKE_NEW',
      'EU 39',
      'Black',
      'BLACK',
      'REGULAR',
      'SHOES',
      'SHOE_EU',
      '39',
      ['gothic', 'formal'],
    ),
    product(
      'Lace Detail Black Midi Dress',
      'dresses-one-pieces',
      560000,
      'LIKE_NEW',
      'M',
      'Black',
      'BLACK',
      'SLIM',
      'DRESS',
      'ALPHA',
      'M',
      ['gothic', 'formal'],
    ),
    product(
      'Charcoal Zip-Up Hoodie',
      'tops',
      285000,
      'GOOD',
      'M',
      'Charcoal',
      'GREY',
      'RELAXED',
      'TOP',
      'ALPHA',
      'M',
      ['gothic', 'streetwear'],
    ),
    product(
      'Burgundy Velvet Evening Top',
      'tops',
      345000,
      'LIKE_NEW',
      'M',
      'Burgundy',
      'RED',
      'SLIM',
      'TOP',
      'ALPHA',
      'M',
      ['gothic', 'formal'],
    ),
    product(
      'Silver Chain Shoulder Bag',
      'bags-wallets',
      410000,
      'GOOD',
      'One size',
      'Silver',
      'METALLIC',
      'REGULAR',
      'BAG',
      'ONE_SIZE',
      'ONE_SIZE',
      ['gothic', 'y2k'],
    ),
  ],
  y2kbyzoya: [
    product(
      'Pink Baby Tee',
      'tops',
      155000,
      'NEW',
      'XS',
      'Pink',
      'PINK',
      'SLIM',
      'TOP',
      'ALPHA',
      'XS',
      ['y2k'],
    ),
    product(
      'Low-Rise Blue Flare Jeans',
      'bottoms',
      320000,
      'GOOD',
      'S',
      'Blue',
      'BLUE',
      'SLIM',
      'BOTTOM',
      'ALPHA',
      'S',
      ['y2k', 'vintage'],
    ),
    product(
      'Lilac Cropped Cardigan',
      'tops',
      245000,
      'LIKE_NEW',
      'S',
      'Lilac',
      'PURPLE',
      'SLIM',
      'TOP',
      'ALPHA',
      'S',
      ['y2k'],
    ),
    product(
      'Y2K Metallic Shoulder Bag',
      'bags-wallets',
      295000,
      'GOOD',
      'One size',
      'Silver',
      'METALLIC',
      'REGULAR',
      'BAG',
      'ONE_SIZE',
      'ONE_SIZE',
      ['y2k'],
    ),
    product(
      'Cherry Red Platform Sandals',
      'other-footwear',
      390000,
      'LIKE_NEW',
      'EU 38',
      'Cherry red',
      'RED',
      'REGULAR',
      'SHOES',
      'SHOE_EU',
      '38',
      ['y2k'],
    ),
  ],
  modestmusepk: [
    product(
      'Sage Embroidered Kurta',
      'tops',
      385000,
      'LIKE_NEW',
      'M',
      'Sage',
      'GREEN',
      'REGULAR',
      'TOP',
      'ALPHA',
      'M',
      ['formal', 'smart-casual'],
    ),
    product(
      'Ivory Pleated Maxi Skirt',
      'bottoms',
      335000,
      'GOOD',
      'M',
      'Ivory',
      'WHITE',
      'RELAXED',
      'BOTTOM',
      'ALPHA',
      'M',
      ['minimalist', 'formal'],
    ),
    product(
      'Dusty Rose Longline Abaya',
      'dresses-one-pieces',
      620000,
      'LIKE_NEW',
      'M',
      'Dusty rose',
      'PINK',
      'RELAXED',
      'DRESS',
      'ALPHA',
      'M',
      ['minimalist', 'formal'],
    ),
    product(
      'Navy Formal Dupatta Set',
      'dresses-one-pieces',
      760000,
      'GOOD',
      'M',
      'Navy',
      'BLUE',
      'REGULAR',
      'DRESS',
      'ALPHA',
      'M',
      ['formal'],
    ),
    product(
      'Deep Green Wedding Guest Dress',
      'dresses-one-pieces',
      850000,
      'LIKE_NEW',
      'M',
      'Deep green',
      'GREEN',
      'TAILORED',
      'DRESS',
      'ALPHA',
      'M',
      ['formal', 'old-money'],
    ),
  ],
  sneakerroompk: [
    product(
      'White Court Sneakers',
      'sneakers',
      450000,
      'LIKE_NEW',
      'EU 42',
      'White',
      'WHITE',
      'REGULAR',
      'SHOES',
      'SHOE_EU',
      '42',
      ['athleisure', 'minimalist'],
    ),
    product(
      'Grey Knit Running Shoes',
      'sneakers',
      520000,
      'GOOD',
      'EU 43',
      'Grey',
      'GREY',
      'REGULAR',
      'SHOES',
      'SHOE_EU',
      '43',
      ['athleisure'],
    ),
    product(
      'Black Training Leggings',
      'bottoms',
      230000,
      'LIKE_NEW',
      'M',
      'Black',
      'BLACK',
      'SLIM',
      'BOTTOM',
      'ALPHA',
      'M',
      ['athleisure'],
    ),
    product(
      'Olive Track Jacket',
      'clothing',
      360000,
      'GOOD',
      'L',
      'Olive',
      'GREEN',
      'REGULAR',
      'OUTERWEAR',
      'ALPHA',
      'L',
      ['athleisure', 'streetwear'],
    ),
    product(
      'Cobalt Performance Tee',
      'tops',
      175000,
      'NEW',
      'L',
      'Cobalt',
      'BLUE',
      'REGULAR',
      'TOP',
      'ALPHA',
      'L',
      ['athleisure'],
    ),
  ],
  studioformal: [
    product(
      'Midnight Tailored Suit Jacket',
      'clothing',
      980000,
      'LIKE_NEW',
      'L',
      'Midnight navy',
      'BLUE',
      'TAILORED',
      'OUTERWEAR',
      'ALPHA',
      'L',
      ['formal', 'old-money'],
    ),
    product(
      'Black Pleated Formal Trousers',
      'bottoms',
      440000,
      'LIKE_NEW',
      'L',
      'Black',
      'BLACK',
      'TAILORED',
      'BOTTOM',
      'ALPHA',
      'L',
      ['formal'],
    ),
    product(
      'Crisp White Dress Shirt',
      'tops',
      310000,
      'GOOD',
      'L',
      'White',
      'WHITE',
      'REGULAR',
      'TOP',
      'ALPHA',
      'L',
      ['formal', 'smart-casual'],
    ),
    product(
      'Burgundy Dinner Blazer',
      'clothing',
      1250000,
      'LIKE_NEW',
      'L',
      'Burgundy',
      'RED',
      'TAILORED',
      'OUTERWEAR',
      'ALPHA',
      'L',
      ['formal'],
    ),
    product(
      'Black Leather Derby Shoes',
      'other-footwear',
      720000,
      'GOOD',
      'EU 43',
      'Black',
      'BLACK',
      'REGULAR',
      'SHOES',
      'SHOE_EU',
      '43',
      ['formal', 'old-money'],
    ),
  ],
  campuscloset: [
    product(
      'University Navy Hoodie',
      'tops',
      240000,
      'GOOD',
      'M',
      'Navy',
      'BLUE',
      'RELAXED',
      'TOP',
      'ALPHA',
      'M',
      ['streetwear', 'athleisure'],
    ),
    product(
      'Relaxed Light-Wash Jeans',
      'bottoms',
      250000,
      'GOOD',
      'M',
      'Light blue',
      'BLUE',
      'RELAXED',
      'BOTTOM',
      'ALPHA',
      'M',
      ['streetwear', 'vintage'],
    ),
    product(
      'Cream Canvas Tote',
      'bags-wallets',
      95000,
      'LIKE_NEW',
      'One size',
      'Cream',
      'BEIGE',
      'REGULAR',
      'BAG',
      'ONE_SIZE',
      'ONE_SIZE',
      ['minimalist'],
    ),
    product(
      'Striped Everyday Shirt',
      'tops',
      195000,
      'GOOD',
      'M',
      'Blue and white',
      'BLUE',
      'RELAXED',
      'TOP',
      'ALPHA',
      'M',
      ['smart-casual'],
    ),
    product(
      'Black Everyday Sneakers',
      'sneakers',
      280000,
      'GOOD',
      'EU 40',
      'Black',
      'BLACK',
      'REGULAR',
      'SHOES',
      'SHOE_EU',
      '40',
      ['streetwear', 'minimalist'],
    ),
  ],
  smallthingspk: [
    product(
      'Espresso Shoulder Bag',
      'bags-wallets',
      365000,
      'LIKE_NEW',
      'One size',
      'Espresso',
      'BROWN',
      'REGULAR',
      'BAG',
      'ONE_SIZE',
      'ONE_SIZE',
      ['old-money', 'smart-casual'],
    ),
    product(
      'Tortoiseshell Sunglasses',
      'small-accessories',
      175000,
      'GOOD',
      'One size',
      'Tortoiseshell',
      'BROWN',
      'REGULAR',
      'ACCESSORY',
      'ONE_SIZE',
      'ONE_SIZE',
      ['vintage', 'old-money'],
    ),
    product(
      'Slim Black Leather Belt',
      'small-accessories',
      145000,
      'LIKE_NEW',
      'One size',
      'Black',
      'BLACK',
      'REGULAR',
      'ACCESSORY',
      'ONE_SIZE',
      'ONE_SIZE',
      ['minimalist', 'formal'],
    ),
    product(
      'Pearl Drop Earrings',
      'small-accessories',
      135000,
      'NEW',
      'One size',
      'Pearl',
      'WHITE',
      'REGULAR',
      'JEWELRY',
      'ONE_SIZE',
      'ONE_SIZE',
      ['old-money', 'formal'],
    ),
    product(
      'Olive Nylon Crossbody',
      'bags-wallets',
      245000,
      'GOOD',
      'One size',
      'Olive',
      'GREEN',
      'REGULAR',
      'BAG',
      'ONE_SIZE',
      'ONE_SIZE',
      ['streetwear', 'techwear'],
    ),
  ],
  karachiedit: [
    product(
      'Cobalt Draped Top',
      'tops',
      285000,
      'LIKE_NEW',
      'M',
      'Cobalt',
      'BLUE',
      'RELAXED',
      'TOP',
      'ALPHA',
      'M',
      ['smart-casual', 'formal'],
    ),
    product(
      'Black Bias-Cut Midi Skirt',
      'bottoms',
      340000,
      'GOOD',
      'M',
      'Black',
      'BLACK',
      'REGULAR',
      'BOTTOM',
      'ALPHA',
      'M',
      ['minimalist', 'formal'],
    ),
    product(
      'Sand Overshirt Jacket',
      'clothing',
      395000,
      'LIKE_NEW',
      'M',
      'Sand',
      'BEIGE',
      'RELAXED',
      'OUTERWEAR',
      'ALPHA',
      'M',
      ['minimalist', 'smart-casual'],
    ),
    product(
      'Rust Satin Dinner Dress',
      'dresses-one-pieces',
      640000,
      'LIKE_NEW',
      'M',
      'Rust',
      'RED',
      'SLIM',
      'DRESS',
      'ALPHA',
      'M',
      ['formal'],
    ),
    product(
      'Modern Square-Toe Sandals',
      'other-footwear',
      440000,
      'GOOD',
      'EU 39',
      'Black',
      'BLACK',
      'REGULAR',
      'SHOES',
      'SHOE_EU',
      '39',
      ['smart-casual', 'formal'],
    ),
  ],
};

export const activeDemoListings: readonly DemoListing[] = Object.entries(activeCollections).flatMap(
  ([seller, products]) =>
    products.map((entry, panel) => ({
      ...entry,
      seller,
      status: 'ACTIVE' as const,
      assetGroup: seller,
      panel,
    })),
);

const lifecycleListings: readonly DemoListing[] = [
  {
    ...product(
      'Mushroom Tailored Vest',
      'tops',
      290000,
      'LIKE_NEW',
      'M',
      'Mushroom',
      'BEIGE',
      'TAILORED',
      'TOP',
      'ALPHA',
      'M',
      ['old-money', 'smart-casual'],
    ),
    seller: 'sundaywardrobe',
    status: 'SOLD',
    assetGroup: 'sold-a',
    panel: 0,
  },
  {
    ...product(
      'Black Parachute Pants',
      'bottoms',
      310000,
      'GOOD',
      'L',
      'Black',
      'BLACK',
      'RELAXED',
      'BOTTOM',
      'ALPHA',
      'L',
      ['streetwear', 'techwear'],
    ),
    seller: 'lahorelayers',
    status: 'SOLD',
    assetGroup: 'sold-a',
    panel: 1,
  },
  {
    ...product(
      'Cream Cable Knit Sweater',
      'tops',
      330000,
      'GOOD',
      'M',
      'Cream',
      'BEIGE',
      'RELAXED',
      'TOP',
      'ALPHA',
      'M',
      ['old-money', 'vintage'],
    ),
    seller: 'neutralarchive',
    status: 'SOLD',
    assetGroup: 'sold-a',
    panel: 2,
  },
  {
    ...product(
      'Vintage Suede Bag',
      'bags-wallets',
      420000,
      'GOOD',
      'One size',
      'Tan',
      'BROWN',
      'REGULAR',
      'BAG',
      'ONE_SIZE',
      'ONE_SIZE',
      ['vintage'],
    ),
    seller: 'secondspinpk',
    status: 'SOLD',
    assetGroup: 'sold-a',
    panel: 3,
  },
  {
    ...product(
      'Black Mesh Party Top',
      'tops',
      225000,
      'LIKE_NEW',
      'M',
      'Black',
      'BLACK',
      'SLIM',
      'TOP',
      'ALPHA',
      'M',
      ['gothic', 'y2k'],
    ),
    seller: 'afterhourscloset',
    status: 'SOLD',
    assetGroup: 'sold-a',
    panel: 4,
  },
  {
    ...product(
      'Maroon Embroidered Shawl',
      'small-accessories',
      360000,
      'GOOD',
      'One size',
      'Maroon',
      'RED',
      'REGULAR',
      'ACCESSORY',
      'ONE_SIZE',
      'ONE_SIZE',
      ['formal', 'vintage'],
    ),
    seller: 'modestmusepk',
    status: 'SOLD',
    assetGroup: 'sold-b',
    panel: 0,
  },
  {
    ...product(
      'Beige Retro Trainers',
      'sneakers',
      410000,
      'GOOD',
      'EU 42',
      'Beige',
      'BEIGE',
      'REGULAR',
      'SHOES',
      'SHOE_EU',
      '42',
      ['vintage', 'athleisure'],
    ),
    seller: 'sneakerroompk',
    status: 'SOLD',
    assetGroup: 'sold-b',
    panel: 1,
  },
  {
    ...product(
      'Emerald Slip Dress',
      'dresses-one-pieces',
      570000,
      'LIKE_NEW',
      'M',
      'Emerald',
      'GREEN',
      'SLIM',
      'DRESS',
      'ALPHA',
      'M',
      ['formal', 'minimalist'],
    ),
    seller: 'karachiedit',
    status: 'SOLD',
    assetGroup: 'sold-b',
    panel: 2,
  },
  {
    ...product(
      'Chocolate Ribbed Top',
      'tops',
      195000,
      'GOOD',
      'M',
      'Chocolate',
      'BROWN',
      'SLIM',
      'TOP',
      'ALPHA',
      'M',
      ['minimalist', 'y2k'],
    ),
    seller: 'campuscloset',
    status: 'DRAFT',
    assetGroup: 'sold-b',
    panel: 3,
  },
  {
    ...product(
      'Navy Utility Vest',
      'clothing',
      285000,
      'GOOD',
      'L',
      'Navy',
      'BLUE',
      'REGULAR',
      'OUTERWEAR',
      'ALPHA',
      'L',
      ['streetwear', 'techwear'],
    ),
    seller: 'lahorelayers',
    status: 'DRAFT',
    assetGroup: 'sold-b',
    panel: 4,
  },
  {
    ...product(
      'Pastel Co-ord Shirt',
      'dresses-one-pieces',
      430000,
      'LIKE_NEW',
      'M',
      'Pastel blue',
      'BLUE',
      'RELAXED',
      'OTHER',
      'ALPHA',
      'M',
      ['minimalist', 'smart-casual'],
    ),
    seller: 'karachiedit',
    status: 'PENDING_REVIEW',
    assetGroup: 'lifecycle',
    panel: 0,
  },
  {
    ...product(
      'Brown Suede Loafers',
      'other-footwear',
      510000,
      'GOOD',
      'EU 41',
      'Brown',
      'BROWN',
      'REGULAR',
      'SHOES',
      'SHOE_EU',
      '41',
      ['old-money', 'vintage'],
    ),
    seller: 'sundaywardrobe',
    status: 'PENDING_REVIEW',
    assetGroup: 'lifecycle',
    panel: 1,
  },
  {
    ...product(
      'Metallic Party Mini Bag',
      'bags-wallets',
      260000,
      'FAIR',
      'One size',
      'Silver',
      'METALLIC',
      'REGULAR',
      'BAG',
      'ONE_SIZE',
      'ONE_SIZE',
      ['y2k'],
    ),
    seller: 'y2kbyzoya',
    status: 'REJECTED',
    assetGroup: 'lifecycle',
    panel: 2,
    rejectionReason:
      'Please add a clearer photo of the interior and disclose the visible strap wear before resubmitting.',
  },
  {
    ...product(
      'Soft Grey Lounge Set',
      'dresses-one-pieces',
      320000,
      'GOOD',
      'M',
      'Grey',
      'GREY',
      'RELAXED',
      'OTHER',
      'ALPHA',
      'M',
      ['athleisure', 'minimalist'],
    ),
    seller: 'campuscloset',
    status: 'ARCHIVED',
    assetGroup: 'lifecycle',
    panel: 3,
  },
  {
    ...product(
      'Vintage Silk Scarf',
      'small-accessories',
      210000,
      'GOOD',
      'One size',
      'Navy and rust',
      'MULTICOLOR',
      'REGULAR',
      'ACCESSORY',
      'ONE_SIZE',
      'ONE_SIZE',
      ['vintage', 'old-money'],
    ),
    seller: 'secondspinpk',
    status: 'ARCHIVED',
    assetGroup: 'lifecycle',
    panel: 4,
  },
] as const;

export const demoListings: readonly DemoListing[] = [...activeDemoListings, ...lifecycleListings];

export const demoAudience = Array.from({ length: 24 }, (_, index) => ({
  authProviderUserId: `${DEMO_NAMESPACE}:audience:${String(index + 1).padStart(2, '0')}`,
  fullName: `Demo Shopper ${String(index + 1).padStart(2, '0')}`,
}));

export const demoQaProfiles = [
  {
    username: 'neutralarchive',
    styles: ['minimalist'],
    colors: ['BEIGE', 'WHITE'],
    fit: 'RELAXED',
    size: 'M',
    budgetMaxMinor: 800000,
  },
  {
    username: 'lahorelayers',
    styles: ['streetwear', 'techwear'],
    colors: ['BLACK', 'RED'],
    fit: 'OVERSIZED',
    size: 'L',
    budgetMaxMinor: 1000000,
  },
  {
    username: 'sundaywardrobe',
    styles: ['old-money', 'smart-casual'],
    colors: ['BEIGE', 'BLUE'],
    fit: 'TAILORED',
    size: 'M',
    budgetMaxMinor: 1500000,
  },
] as const;
